version: '3.4'

services:
  application:
    image: datagen-avro-schema-generator
    volumes:
      - /tmp:/tmp
    build: .
    environment:
      - JSONFILE=/tmp/user.json
      - TYPENAME=Sometype

